name: Xodium CI/CD

on:
  push:
    branches: [main]
    paths:
      - "irp/**"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.create_release.outputs.url }}
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
      SHA1: ${{ steps.calculate_sha1.outputs.SHA1 }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - id: get_version
        name: Get Version
        run: echo "VERSION=$(jq -r '.version' version.json)" >> $GITHUB_OUTPUT

      - id: packsquash
        name: Create Zip & Optimize with Packsquash
        uses: ComunidadAylas/PackSquash-action@v4.0.3
        with:
          packsquash_version: latest-unstable
          options: |
            pack_directory = 'irp'
            output_file_path = 'irp_${{ steps.get_version.outputs.VERSION }}.zip'

      - id: calculate_sha1
        name: Calculate SHA1
        run: echo "SHA1=$(sha1sum "irp_${{ steps.get_version.outputs.VERSION }}.zip" | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - id: create_release
        name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ contains(github.event.head_commit.message, '.draft') }}
          files: irp_${{ steps.get_version.outputs.VERSION }}.zip
          body: |
            Direct Download Link: https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/irp_${{ steps.get_version.outputs.VERSION }}.zip
            SHA-1 Hash: ${{ steps.calculate_sha1.outputs.SHA1 }}
          generate_release_notes: true
          prerelease: ${{ contains(github.event.head_commit.message, '.pre') }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}

  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - id: uspr
        name: Update server.properties remotely
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            sed -i \
              -e "s|^resource-pack=.*|resource-pack=https://github.com/${{ github.repository }}/releases/download/${{ needs.release.outputs.VERSION }}/irp_${{ needs.release.outputs.VERSION }}.zip|" \
              -e "s|^resource-pack-sha1=.*|resource-pack-sha1=${{ needs.release.outputs.SHA1 }}|" \
              ${{ secrets.SERVER_PROPERTIES_PATH }}
